#!/usr/bin/env bash
# Configure HAproxy with version equal or greater than 1.5 so that it send traffic to web-01 and web-02
sudo apt -y update
sudo apt install -y haproxy
sudo echo -e "ENABLED=1" | sudo  tee -a /etc/default/haproxy
sudo echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver gc-1822-web-01-1607318804 35.237.110.243:80 check\n\tserver gc-1822-web-02-1608529112 35.237.226.73:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
