#!/usr/bin/env bash
# Create a file containing the PID and send some traps.
echo $$ >> /var/run/holbertonscript.pid

while true; do
	echo "To infinity and beyond"
	trap "echo I hate the kill command" SIGTERM
	trap "sudo rm /var/run/holbertonscript.pid; exit" SIGTERM SIGQUIT
	trap "echo Y U no love me?!" SIGINT
	sleep 2
done
