#!/usr/bin/env bash
# Create a file containing the PID and send some traps.
echo $$ >> /var/run/holbertonscript.pid

while true; do
	trap "echo I hate the kill command; sudo rm /var/run/holbertonscript.pid; exit" SIGTERM
	trap "sudo rm /var/run/holbertonscript.pid" SIGQUIT
	trap "echo Y U no love me?!" SIGINT
	echo "To infinity and beyond"
	sleep 2
done
