#!/usr/bin/env bash
cp /etc/hosts /tmp/host_updated.new

sed -i -e 's/127.0.0.1/127.0.0.2/g' /tmp/host_updated.new
sed -i -e 's/157.240.11.35/8.8.8.8/g' /tmp/host_updated.new

cp /tmp/host_updated.new /etc/hosts
