#!/usr/bin/env bash
#comment
cp /etc/hosts ~/host_updated.new
sed -i -e 's/127.0.0.1/127.0.0.2/g' ~/host_updated.new
echo "8.8.8.8 facebook.com" >> ~/hosts_updated.new
cp -f ~/host_updated.new /etc/hosts
